# Generated by Django 6.0.6 on 2026-07-04 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='room_id',
            new_name='room',
        ),
    ]
