# Generated by Django 6.0.6 on 2026-07-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_rename_room_id_booking_room'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ['date_start']},
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='end_at',
            new_name='date_end',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='start_at',
            new_name='date_start',
        ),
    ]
