### Создание брони
POST http://127.0.0.1:8000/bookings/create/
Content-Type: application/json

{
  "room_id": 3,
  "date_start": "2022-02-14",
  "date_end": "2022-02-18"
}
### Создание комнаты
POST http://127.0.0.1:8000/rooms/create/
Content-Type: application/json

{
  "description": 123,
  "price": 123
}

### Удаление брони
# Ожидаемый ответ сервера: 204 No Content
DELETE http://127.0.0.1:8000/bookings/7/delete/
Accept: application/json

### Удаление комнаты
# Ожидаемый ответ сервера: 204 No Content
DELETE http://127.0.0.1:8000/rooms/2/delete/
Accept: application/json

### Получение списка комнат с фильром по цене
# Можно передать без фильтра, с фильтром по цене или по дате создания
# Ожидаемый ответ сервера: 200 OK
GET http://127.0.0.1:8000/rooms/list/?ordering=price
Accept: application/json

### Полное обновление брони (PUT)
# Обязательно передаются все требуемые поля
# Ожидаемый ответ сервера: 200 OK
PUT http://127.0.0.1:8000/bookings/8/update/
Content-Type: application/json

{
  "room_id": 3,
  "date_start": "2022-01-31",
  "date_end": "2022-02-14"
}

### Полное обновление комнаты (PUT)
# Обязательно передаются все требуемые поля
# Ожидаемый ответ сервера: 200 OK
PUT http://127.0.0.1:8000/rooms/1/update/
Content-Type: application/json

{
  "description": "description first room",
  "price": 1234
}